name: Auto-tag
on:
  push:
    branches:
      - master
jobs:
  autotag:
    name: Auto-tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Compute next tag name
        id: compute_tag
        shell: pwsh
        continue-on-error: true
        run: |
          $versions = $(git tag --sort=version:refname)
          $lastTag = $($versions | Select -Last 1)
          if ([string]::IsNullOrEmpty($lastTag)) {
            $newTag = "1.0.0-pre.1"
          } else {
            $nonPreVersion = $($lastTag.Split('.') | Select-Object -First 3) -join '.' -replace ".pre", ""
            if ($versions -contains $nonPreVersion) {
              $lastTag = $nonPreVersion
            }
            $stationaryVersion = $($lastTag.Split('.') | Select-Object -SkipLast 1) -join '.'
            $lastDigit = ([int]$lastTag.Split('.')[-1]) + 1
            if ($lastTag -match "-pre") {
              $newTag = $stationaryVersion + "." + [string]$lastDigit
            } else {
              $newTag = $stationaryVersion + "." + [string]$lastDigit + "-pre.1"
            }
          }
          Write-Output "::set-output name=tag_name::$newTag"
        
      - name: Auto-tag repo
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{secrets.GIT_TOKEN}}
          tag: "${{steps.compute_tag.outputs.tag_name}}"
