name: Tests

on:
  push:
    tags:
      - '*'
    branches:
      - '**'
      - '!master'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ github.token }}
      - name: Run Tests
        run: dotnet test
        shell: pwsh
